services:
  mongodb:
    image: mongo
    container_name: airkart-db
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    networks:
      - airkart-network

  backend:
    build: .
    container_name: "airkart-backend_v${TAG}"
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    env_file:
      - .env
    networks:
      - airkart-network
      
volumes:
  db_data:

networks:
  airkart-network:
    driver: bridge
