version: '3'
services:
  mongodb:
    image: mongo
    container_name: airkart-db
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  app:
    build: .
    container_name: airkart-backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - DB_NAME=airkart
      - API_VERSION=v1
      - JWT_SECRET=$pafjwePla@fadj1l2j%kajsdj1290!fjadlk@jkljdajd$k
      - JWT_EXPIRE=7d
      - JWT_COOKIE_EXPIRE=7